version: '3.8'

services:
  webcam-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live_webcams_app
    restart: always
    ports:
      - "3300:3300"
    environment:
      - PORT=3300
      - NODE_ENV=production
      - WINDY_API_KEY=${WINDY_API_KEY}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3300/"]
      interval: 30s
      timeout: 5s
      retries: 3
